server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: "services-logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "services"
          __path__: /var/log/*.log
    pipeline_stages:
      - json:
          expressions:
            correlationId: metadata.correlationId
            requestId: metadata.requestId
            traceId: metadata.traceId
            spanId: metadata.spanId
            timestamp: metadata.timestamp
            serviceName: metadata.serviceName
            environment: metadata.environment
            version: metadata.version
            hostname: metadata.hostname
            severity: metadata.severity
            caller: metadata.caller
      - labels:
          correlationId:
          traceId:
          spanId:
          serviceName:
          environment:
          version:
          severity:
          caller:
      - timestamp:
          source: timestamp
          format: RFC3339
